# Generated by Django 3.1.5 on 2021-01-10 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210110_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
