# Generated by Django 3.1.5 on 2021-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210110_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
